### ISSUE TITLE
Idiot's Guide

### ISSUE THREAD

**Issue by BT-Justice** [khaytsus/gqrx-scan#10]
I need an Idiot's Guide to installing and setting up gqrx-scan,  I am using the version of GQRX with the bookmarks option.  This is what I have done so far using Ubuntu MATE 14.04.2 LTS:

1) Open Terminal.
2) Type in:  git clone https://github.com/khaytsus/gqrx-scan/
3) Type in:  cd gqrx-scan
4) Verifying I am in the gqrx-scan directory, type in:  gqrx-scan --type gqrxfile --pause 2

I get an error saying:  gqrx-scan: command not found

I am assuming I installed it correctly using the above.

**Comment by khaytsus** [comment]
Try specifying to use perl, like this: perl gqrx-scan --type gqrxfile --pause 2

Most likely gqrx-scan is not executable, nor is it in your path.

**Comment by BT-Justice** [comment]
I had to 'sudo apt-get install libnet-telnet-perl' and then use your command.  All seems to be working.  Thank you so much :)

**Comment by khaytsus** [comment]
Great, glad to know this is working!  Perhaps I should add a little more info to the readme to cover this..  I unfortunately forget that I've use Unix so long I don't think about the requirements to run scripts etc sometimes.

**Comment by Si3o2** [comment]
Hi @khaytsus, I know this is closed, but I am having a similar issue as @BT-Justice.

I did the 'sudo apt-get install libnet-telnet-perl' and then tried your 'perl gqrx-scan -type gqrxfile - pause 1' command. How do I enable remote control via TCP in GQRX? If I open GQRX to enable it my terminal is busy. I've opened GQRX and configured the IP and port settings, but when I close out of GQRX and then return to my terminal, I have the same error. Any thoughts on what I'm doing wrong?

Let me know if you have any questions. Thanks.

**Comment by khaytsus** [comment]
On 07/12/2016 12:02, Si3o2 wrote:
> Hi @khaytsus [1], I know this is closed, but I am having a similar issue as @BT-Justice [2]. 
> 
> I did the 'sudo apt-get install libnet-telnet-perl' and then tried your 'perl gqrx-scan -type gqrxfile - pause 1' command. How do I enable remote control via TCP in GQRX? If I open GQRX to enable it my terminal is busy. I've opened GQRX and configured the IP and port settings, but when I close out of GQRX and then return to my terminal, I have the same error. Any thoughts on what I'm doing wrong? 

GQRX has to be running; this script uses it to do all of the actual SDR work.  The script just controls GQRX.

Enabling the TCP control in GQRX is mentioned here:  http://gqrx.dk/doc/remote-control

Please note that GQRX does NOT save the setting for TCP enabled.  It saves the TCP _settings_ themselves, but not that it's enabled.  So each time you launch GQRX you have to enable the TCP remote control setting.  I have logged an issue for this in the GQRX github long ago but no change was made so far.  https://github.com/csete/gqrx/issues/219

Hopefully this helps.

> Let me know if you have any questions. Thanks. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4]. 
> 
> 	* 
> 
> Links:
> ------
> [1] https://github.com/khaytsus
> [2] https://github.com/BT-Justice
> [3] https://github.com/khaytsus/gqrx-scan/issues/10#issuecomment-232094958
> [4] https://github.com/notifications/unsubscribe/AFLzdQXQBY5dGOFtl6Wg2dQjDZ1ji_Gqks5qU7qUgaJpZM4FbqvC

-- 
Walter Francis

khayts.us
theblackmoor.net
unlimitedphoto.com

**Comment by Si3o2** [comment]
Okay thanks for the reply. I was able to get it up and running this afternoon. Apparently it was a simple issue with not having the TCP remote configured correctly. Thanks again.
