### ISSUE TITLE
is this record only? or does it output audio as well

### ISSUE THREAD

**Issue by vo1pwf** [khaytsus/gqrx-scan#13]
Just wondering while scanning do you hear the signal or does it only record to a file for listening later

**Comment by khaytsus** [comment]
Script doesn't really control that part, it's whatever GQRX would do for that setting.  If you have GQRX muted in your sound settings or such, you won't hear anything.

For me, I tend to make sure the GQRX squelch is the same as what I have set as my level in the script or lower (ie:  Squelch open), if you have it set the other way (Squelch is very tight, say -30 signal) and you have your script set to something more open (Squelch -60 for example) it will record an empty sound file as GQRX is squelched.  So it's better to have GQRX's squelch set to open or very close (depends on your noise level) if you're recording so you get all of your recordings.  Same thing applies for scanning without recording too.

I have an open bug on GQRX about the fact that you can't set squelch from the TCP interface but the author challenged me to add the interface myself I haven't figured out how to fix it in GQRX and submit a patch, so it may or may never get fixed on the GQRX side in bug https://github.com/csete/gqrx/issues/282

Does this answer your question?

**Comment by vo1pwf** [comment]
Yes...many thanks

On January 3, 2016 2:31:16 PM NST, khaytsus <notifications@github.com> wrote:
>Script doesn't really control that part, it's whatever GQRX would do
>for that setting.  If you have GQRX muted in your sound settings or
>such, you won't hear anything.
>
>For me, I tend to make sure the GQRX squelch is the same as what I have
>set as my level in the script or lower (ie:  Squelch open), if you have
>it set the other way (Squelch is very tight, say -30 signal) and you
>have your script set to something more open (Squelch -60 for example)
>it will record an empty sound file as GQRX is squelched.  So it's
>better to have GQRX's squelch set to open or very close (depends on
>your noise level) if you're recording so you get all of your
>recordings.  Same thing applies for scanning without recording too.
>
>I have an open bug on GQRX about the fact that you can't set squelch
>from the TCP interface but the author challenged me to add the
>interface myself I haven't figured out how to fix it in GQRX and submit
>a patch, so it may or may never get fixed on the GQRX side in bug
>https://github.com/csete/gqrx/issues/282
>
>Does this answer your question?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/khaytsus/gqrx-scan/issues/13#issuecomment-168523872

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by khaytsus** [comment]
Great, hope you enjoy the script :)
