### ISSUE TITLE
Use of uninitialized value warnings.

### ISSUE THREAD

**Issue by starvald** [khaytsus/gqrx-scan#16]
**Haven't used gqrx-scan for little while but getting these errors, not sure if it's due to the latest commits or Archlinux, still scans and records wav's though.**

`lee@Antergos:~/gqrx-scan$ ./marine.sh 
No default config file found..

Starting in gqrxfilemode scanning for channels: 13 14 15 17 

Can't write to /home/lee/baofeng/gqrxscan.log, logging to /tmp/gqrxscan.log
On detection of signal will wait until channel is clear

Channel/Frequency pause time:  0.5s
Delaylevel: [-75]  Delaytime: [5]

Loaded 71 lines from GQRX CSV file

Use of uninitialized value $c_m in concatenation (.) or string at ./gqrx-scan line 886.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 886.
Use of uninitialized value $c_m in concatenation (.) or string at ./gqrx-scan line 886.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 886.
Use of uninitialized value $c_g in concatenation (.) or string at ./gqrx-scan line 899.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 899.
Use of uninitialized value $c_c in concatenation (.) or string at ./gqrx-scan line 899.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 899.
Use of uninitialized value $c_c in concatenation (.) or string at ./gqrx-scan line 899.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 899.
--- Scan: 00:00:00:00 - Most Active: na (0) - Record: 00:00:00:00 (0) ---
Use of uninitialized value $c_r in concatenation (.) or string at ./gqrx-scan line 561.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 561.
Use of uninitialized value $c_m in concatenation (.) or string at ./gqrx-scan line 578.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 578.
Use of uninitialized value $l in concatenation (.) or string at ./gqrx-scan line 600.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 600.
Use of uninitialized value $l in concatenation (.) or string at ./gqrx-scan line 600.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 600.
 156.000 000 -        marine CH0 - [    FM] [-77.4 / -77.4] [-75] [Line  13]
Use of uninitialized value $c_r in concatenation (.) or string at ./gqrx-scan line 561.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 561.
Use of uninitialized value $c_m in concatenation (.) or string at ./gqrx-scan line 578.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 578.
Use of uninitialized value $l in concatenation (.) or string at ./gqrx-scan line 600.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 600.
Use of uninitialized value $l in concatenation (.) or string at ./gqrx-scan line 600.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 600.
 156.375 000 -         Humber CG - [    FM] [-83.0 / -83.0] [-75] [Line  14]
Use of uninitialized value $c_r in concatenation (.) or string at ./gqrx-scan line 561.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 561.
Use of uninitialized value $c_m in concatenation (.) or string at ./gqrx-scan line 578.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 578.
Use of uninitialized value $l in concatenation (.) or string at ./gqrx-scan line 600.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 600.
Use of uninitialized value $l in concatenation (.) or string at ./gqrx-scan line 600.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 600.
 156.600 000 -          port ops - [    FM] [-83.5 / -83.5] [-75] [Line  15]
Use of uninitialized value $c_r in concatenation (.) or string at ./gqrx-scan line 561.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 561.
Use of uninitialized value $c_m in concatenation (.) or string at ./gqrx-scan line 578.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 578.
Use of uninitialized value $l in concatenation (.) or string at ./gqrx-scan line 600.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 600.
Use of uninitialized value $l in concatenation (.) or string at ./gqrx-scan line 600.
Use of uninitialized value $r in concatenation (.) or string at ./gqrx-scan line 600.`

**Comment by khaytsus** [comment]
Looks like ANSI/color is disabled.  I looked at making this clean a while back but never did, but I probably should clean this up since I did set it up to be able to not use ANSI/colors.  I'll work on this.

**Comment by khaytsus** [comment]
Pull the latest and give it a try, per some suggestion I simply assigned null values to these variables so when they're not used, they are valid, but non-printing characters and should show nothing in the terminal.  Hope this fixes it, if not, reopen and let me know!

**Comment by starvald** [comment]
it's fixed, many thanks.
