### ISSUE TITLE
Ubuntu 16.04 issues

### ISSUE THREAD

**Issue by sgofferj** [khaytsus/gqrx-scan#17]
Under Ubuntu 16.04, gqrx-scan doesn't seem to connect to gqrx 2.61. It complains when the remote control is disabled but when it's enabled, it doesn't seem to connect. I see lots of the following errors:

Can't write to /home/sgofferjgqrxscan.log, logging to /tmp/gqrxscan.log

Use of uninitialized value $tmpfreq in scalar chomp at ./gqrx-scan line 279.

Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 11.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 12.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 13.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 14.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 15.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 16.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 17.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 18.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 19.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 20.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 21.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 22.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 23.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 24.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 25.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 26.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 27.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 28.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 29.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 30.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 31.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 32.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 33.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 34.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 35.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 36.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 37.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 38.
Use of uninitialized value $freq in string eq at ./gqrx-scan line 864, <$csvfile> line 39.

Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $level in string ne at ./gqrx-scan line 542.
 118.700 000 -           TMP Tower - [    AM] [ -150 /  -150] [Line   6]
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $level in string ne at ./gqrx-scan line 542.
 119.700 000 -   TMP TowerApproach - [    AM] [ -150 /  -150] [Line   7]
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $level in string ne at ./gqrx-scan line 542.
 120.250 000 -        TMP Approach - [    AM] [ -150 /  -150] [Line   8]
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $level in string ne at ./gqrx-scan line 542.
 126.200 000 -        TMP Approach - [    AM] [ -150 /  -150] [Line   9]
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $level in string ne at ./gqrx-scan line 542.
 133.550 000 -            TMP ATIS - [    AM] [ -150 /  -150] [Line  10]
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.
Use of uninitialized value $tmpfreq in string eq at ./gqrx-scan line 403.

and so on...

**Comment by sgofferj** [comment]
Wireshark shows that there's an initial connection handshake but nothing after that.

**Comment by sgofferj** [comment]
Bug is in gqrx IP settings.
*** Remote connection attempt from ::ffff:127.0.0.1 (not in allowed list)                                                                                                   
*** Remote connection attempt from ::ffff:192.168.10.1 (not in allowed list)

**Comment by khaytsus** [comment]
Ah, yes, I've seen this on fresh installs too.  I'll make a note in the gqrx scan readme, do you think that's sufficient for that issue?  As for the others, it should fail immediately..  I'm a bit confused about that.  It should say something like..

Unable to open connection to GQRX at line 262

Make sure TCP Remote is enabled and listening on 127.0.0.1 and port 7356

Also, make sure you're up to date, I fixed a few issues with CSV loading, it wasn't sanitizing or sanity checking input very well.

**Comment by sgofferj** [comment]
Yeah, I was planning to report a bug for gqrx on that. Just didn't get to that yet. It seems, the allowed IP settings in gqrx are messed up. If you just enter an IPv4 address, it doesn't work. You have to enter ::ffff:<IPv4 address> to make it work properly which is a bit nasty.
