### ISSUE TITLE
Mode Filter Option

### ISSUE THREAD

**Issue by pekpek** [khaytsus/gqrx-scan#3]
Is there a way to control the Mode Filter (such as Wide, Normal, Narrow, User )?

**Comment by khaytsus** [comment]
I've finally fixed this, but I don't see the code to do this in GQRX 2.6.1 yet, it appears to only be in the Master branch.  This did cause some CSV file compatibility breakage but it does detect the line is invalid (missing the bandwidth) and refers to the README.  It does work for me, and hopefully the code to support it in GQRX will hit release eventually!
